### ISSUE TITLE
concoct takes forever to load composition file when kmer length is set to 9 or more

### ISSUE THREAD

**Issue by yoyohashao** [BinPro/CONCOCT#147]
Hey guys,
the default value of kmer length is 4 and 5 works as well. But when I set the kmer length to 9 or more, concoct feels like stuck at the initial step. No error message but the composition file couldn't be loaded. Any idea about this issue? The input composition file is <600MB. 
Many thanks

**Comment by alneberg** [comment]
Hi @yoyohashao,

yeah this is not really unexpected since the number of kmers generated in concoct will be on the order of (4^9)/2 = 131072. This will be stored per contig, so you could quite likely be running out of memory. I guess there could be approaches to fix this issue in the terms of loading the data but in order to finish running the algorithm you can't have too many dimensions. I guess the number of kmers present in the data will flatten out when increasing the k, but for k=9 and larger, the number of kmers present in the dataset will still be too big for the algorithm to be efficient enough.

Finally, I don't think its a good idea to use a high k. The phylogenetic signal in the contigs will probably drown in the nucleotide differences in the kmers.

Hope you can accept this answer.

Cheers,
Johannes

**Comment by yoyohashao** [comment]
Gotcha Johannes.

Thanks for answering

Fang Liu
PhD Candidate
Rm. 3-410 School of Life Sciences and Biotechnology
Shanghai Jiaotong University
Shanghai,China 200240
https://www.researchgate.net/profile/Fang_Liu37
