### ISSUE TITLE
Parallelization of vbgmm

### ISSUE THREAD

**Issue by mherold1** [BinPro/CONCOCT#158]
Hello,

I was trying to run concoct binning for reads of 53 samples mapping to ~ 7,5 mio. contigs and with max expected clusters of 200. The binning did not finish in the 5 days maximum walltime in our hpc, so I was wondering if I can increase the number of threads that vbgmm runs on (I guess the other alternative would be to reduce the number of expected clusters?). 
I found the following line in the header file `c-concoct/vbgmmmodule.h`: 
`#define N_RTHREADS       10`
Could I change this parameter to e.g. 24 and rerun setup.py to use more threads? I am not really sure how the vbgmm module is compiled. 

Thank you for your help. Best regards,

Malte

**Comment by alneberg** [comment]
Hi Malte,

I'm sorry to say that the parallelization of vbgmm is crude at this moment. It is basically using one thread for each run of the clustering before deciding on the best one in the end. It is by default running 10 threads and 10 initializations so ensuring that you have 10 cores available to concoct could be an improvement. But assuming you have at least 10 cores available when you run it in the first place you would not gain any speed by running on 24 threads instead. 

Potential solutions to making it run faster:
  - Use only coverage (this is quite untested but it seems that especially when using this many samples you will not gain much from using the nucleotide composition). You can accomplish this by giving -k 0 as argument to concoct.
  - Use a smaller subset of your contigs, by using a larger length cutoff.

The dataset you describe is indeed quite big, and I would myself try out the first method, but be aware that this is not anything we have tested thoroughly yet. 

I don't think the number of expected clusters have a huge impact on the execution speed. It does have a impact on the results however, and the recommendation is to use an approximately 4 times larger number than you would expect to have as a result. So I would guess for your dataset that is probably larger than the default 400 rather than smaller?

Hope any of this is useful.

Cheers,
Johannes

**Comment by mherold1** [comment]
Thanks for the reply.

During the first test I used 10 cores for the run to match the default 10 threads. I was just wondering if I had more cores available (e.g. 24 on 1 node or possible even more), could I change the N_RTHREADS so that vbgmm makes use of 24 cores instead. Can I do that by simply editing the headerfile and recompiling the module? How would I recompile the module, simply by rerunning setup.py?

Changing the number of expected clusters was actually suggested by a collegue how tried concoct with a different dataset. For him reducing the number from initially 500 to 200 decreased the runtime by quite a bit. I agree that for my dataset I should probably have chosen a higher number, the 200 was just for an initial test. 

I will consider using only coverage, but I do not understand why the nucleotide composition has less of an impact when many samples are used. Using a smaller number of contigs is of course also a possibilty. Thank you for the suggestions.
 
Cheers,

Malte

**Comment by alneberg** [comment]
Yes, changing N_RTHREADS and compiling could probably work, but you would not gain any speed on it due to the way concoct uses the threads. It will not use them to speed up, but only to run more iterations and thus potentially improve the clustering results. So you would need to do some redesigning of the implementation in order to parallelize it better.

I suspect the composition data is just less informative compared to the coverage information. But most projects are lacking the number of samples you need in order to gain that information and thus composition is also useful.

Johannes

**Comment by mherold1** [comment]
Ah thank you for explaining that again, I did not get it the first time. 

I will see what I can try and I'll let you know how it goes.

Thanks again.

**Comment by alneberg** [comment]
No problem.

Good luck!
Johannes
