### ISSUE TITLE
cut_up_fastas.py strictly necessary for concoct?

### ISSUE THREAD

**Issue by jvollme** [BinPro/CONCOCT#173]
I do not quite understand the requirement for cutting large contigs into smaller chunks when using concoct. 
Do you consider this a strict necessity or rather a recommendation? 
Would you say bins generated with concoct using uncut contigs directly would be generally unreliable?

Using the uncut contigs instead would make it easier to directly compare the binning results with those of other binners, which do not usually require pre-cutting large contigs into chunks.

**Comment by inodb** [comment]
Thanks for your question @jvollme !

From the paper: Contigs were cut up into non-overlapping fragments of 10 kilobases in order to (1) give more weight to large contigs and (2) mitigate the effect of local assembly errors by having the potential to separate erroneous parts during clustering.

So yeah it would be better to cut them up. If all the contigs end up in the same bin, you can easily merge them again by look at the fasta id. It just appends some extra number. I guess you could also assign all the cutup contigs to the bin where the most cut up contigs get assigned

**Comment by inodb** [comment]
Closing this for now
