### ISSUE TITLE
How can I obtain the fasta sequence from the final bins?

### ISSUE THREAD

**Issue by rotoscan** [BinPro/CONCOCT#182]
I was able to run the concoct software and I have a lot of output. I was even able to plot the pdf visualization file for the generated bins. I would like, however, to obtain the fasta sequence for each generated bin. How can I do it?

My outputs are:
args.txt                         
pca_variances_gt1000_dim10.csv  
pca_variances_gt1000_dim19.csv 
pca_variances_gt1000_dim9.csv  r8.csv                      variances_gt1000_dim15.csv  
variances_gt1000_dim5.csv
clustering_gt1000.csv            pca_variances_gt1000_dim11.csv  pca_variances_gt1000_dim1.csv   r0.csv                         r9.csv                      variances_gt1000_dim16.csv  variances_gt1000_dim6.csv
log.txt                          pca_variances_gt1000_dim12.csv  pca_variances_gt1000_dim2.csv   r1.csv                         responsibilities.csv        variances_gt1000_dim17.csv  variances_gt1000_dim7.csv
means_gt1000.csv                 pca_variances_gt1000_dim13.csv  pca_variances_gt1000_dim3.csv   r2.csv                         variances_gt1000_dim0.csv   variances_gt1000_dim18.csv  variances_gt1000_dim8.csv
original_data_gt1000.csv         pca_variances_gt1000_dim14.csv  pca_variances_gt1000_dim4.csv   r3.csv                         variances_gt1000_dim10.csv  variances_gt1000_dim19.csv  variances_gt1000_dim9.csv
PCA_components_data_gt1000.csv   pca_variances_gt1000_dim15.csv  pca_variances_gt1000_dim5.csv   r4.csv                         variances_gt1000_dim11.csv  variances_gt1000_dim1.csv   vbl.csv
pca_means_gt1000.csv             pca_variances_gt1000_dim16.csv  pca_variances_gt1000_dim6.csv   r5.csv                         variances_gt1000_dim12.csv  variances_gt1000_dim2.csv
PCA_transformed_data_gt1000.csv  pca_variances_gt1000_dim17.csv  pca_variances_gt1000_dim7.csv   r6.csv                         variances_gt1000_dim13.csv  variances_gt1000_dim3.csv
pca_variances_gt1000_dim0.csv    pca_variances_gt1000_dim18.csv  pca_variances_gt1000_dim8.csv   r7.csv                         variances_gt1000_dim14.csv  variances_gt1000_dim4.csv

**Comment by alneberg** [comment]
Hello!

You can extract all bins as fasta with the script:
https://github.com/BinPro/CONCOCT/blob/master/scripts/extract_fasta_bins.py

However the contigs will still be cutup so you might want to consider merging the binning for these contigs first. If you think a majority vote system is good, you can use our script for that here https://github.com/EnvGen/toolbox/blob/master/scripts/concoct/merge_cutup_clustering.py

and after that run the first script I mentioned. We also recommend quality filtering your bins with e.g. CheckM so that you don't trust all bins blindly.

Cheers,
Johannes
