### ISSUE TITLE
Format of cluster file with linkage information

### ISSUE THREAD

**Issue by jfrank87** [BinPro/CONCOCT#209]
Dear developers,

After hierarchical clustering of the clusters based on linkage information, I obtain a 4 column file similar to the test data deposited here: [clustering_gt_1000_l.csv](https://github.com/BinPro/CONCOCT-test-data/blob/master/concoct-output/clustering_gt1000_l.csv)

However, for some reason, I am not able to extract fasta bins using this file. I've opened an issue about this a while ago  (#167). This issue has not yet been addressed, however I would like to know:

What do the 3 last columns of the clustering file describe?

Thanks in advance and kind regards,
Jeroen

**Comment by alneberg** [comment]
Sorry to keep you waiting. The honest answer is that I don't know. The linkage script hasn't been maintained in a few years and we never actually used it since we didn't see an advantage to the clustering results from it compared to just using concoct.

Judging from the Validate.pl script I can decode that the second column contains the cluster id. So you can use this file as a regular clustering file by just disregarding the last two columns.

Cheers,
Johannes
