### ISSUE TITLE
Question about running concoct: Large co-assembly vs multiple sample-based assemblies

### ISSUE THREAD

**Issue by franciscozorrilla** [BinPro/CONCOCT#224]
Hello, its me again with more questions!

I am wondering if it is possible to run concoct on each individual sample, instead of running concoct on the entire assembly? My research question is aimed more towards knowing what species are in what sample, rather than in the entire dataset. Would this be a feasible approach, or does concoct **need** to run on the assembly of the entire dataset? If it is not possible to run concoct on each individual sample and an assembly of the entire dataset is needed, is it then possible to know which bins are present in which samples ?

Regards,
Francisco

**Comment by alneberg** [comment]
Hello @franciscozorrilla,

this is an excellent question. CONCOCT can handle both scenarios but there are pros and cons with both methods. For each individual sample assembly used with CONCOCT, one has to have coverage values for every other sample. Therefore if you have N samples, you have to run the mapping NxN times and generate NxN number of .bam files. This can become both computationally and storage-wise very heavy.

For this reason I've successfully used Kallisto to estimate coverage instead of a regular mapper. This is faster and uses less storage. However you need to apply a custom parser to get the coverage table from the abundance files. I have such a script here: https://github.com/EnvGen/toolbox/blob/master/scripts/kallisto_concoct/input_table.py

This way of running CONCOCT is not yet directly supported in the package itself, therefore its a bit more messy.

Thanks,
Johannes

**Comment by franciscozorrilla** [comment]
Hi Johannes,

Could you elaborate a bit on the increasing the base length cut off suggestion? I do not understand this, are you referring to contigs? Is this something I would do in the assembly step or beforehand?

Great! I will try out the new CONCOCT version as soon as the mapping/removing duplicates is finished in my dataset. I have already built my pipeline based on the old example present in readthedocs (any idea when this will be up again?) with some modifications. Do you foresee any problems I may have switching to the new version considering my pipeline is based on the old example?

Best wishes,
Francisco

**Comment by alneberg** [comment]
I think you should start by running the latest version of concoct with default parameters and using as many cores as you have available. Remember to set the number of cores as a parameter to concoct as well.

In case this is too slow, you could decrease the data size by not including the shortest contigs into the binning step, for example using:

`--length_threshold 2000`

as a parameter to concoct would exclude all contigs between 1000 and 2000 and therefore concoct will run much faster. However, these will then be excluded also from the results of course, so the binning results will likely be worse.

I had a look at your repository thesis_pipeline which I assume is the pipeline you refer to? Up to running concoct, you don't have to change anything. But I think you should consider using the new script `merge_cutup_clustering.py` to get your bins in terms of the original contigs instead of the cutup ones.

Check the README for the new version to see the basic usage examples.

Also, I would recommend using the tool CheckM instead of the prodigal+rpsblast+COGfilter step. It's much more sensitive and more well maintained compare to our in-house scripts.

Good Luck!
Johannes

**Comment by franciscozorrilla** [comment]
Hi Johannes,

This is very helpful information, thank you for your comprehensive response!

I just realized I forgot to respond to your question regarding my computational setup: I am using hebbe (which is part of C3SE/SNIC). I have access to nodes with 64, 128, 512, and 1024 GB RAM. Each node has 20 CPU cores, except the 1024 GB RAM node which has 24 CPU cores ( I have been using this one for the megahit assembly and other computationally intense tasks). Generally I only use one node. Do you think the 1024 GB RAM node with 24 CPUs is overkill for running CONCOCT on my (large) dataset?

Ah I see. I had not realized that the length_threshold was a CONCOCT parameter! I understand now.

Thank you so much for taking a look at my pipeline! Yes that is the one. I will definitely take a look at the merge_cutup_clustering.py script and the README file.

Ah yes, I believe you have already suggested Check'M to me. I have taken a look at it but then got distracted by other tools. If I understand correctly, this tool is used to asses the quality of draft genomes? So if one of my bins has a bad score I would discard it? And I would have to use the companion tool Groop'M as well? Do these tools do any sort of taxonomic profiling as well or is it strictly bin quality control?

Best wishes and thanks again,
Francisco

**Comment by johnne** [comment]
@alneberg, theoretically you wouldn't need to do the full cross-mapping of all samples for each assembly right? The number of bins generated by CONCOCT maxes out at around 40 samples or so if I remember correctly, so you could select 40 samples at random and map those against each individual assembly? That would cut down processing a lot. I guess you'd want samples that cover the diversity of all samples well enough though which may be tricky depending on the project. But perhaps it is applicable here?

**Comment by alneberg** [comment]
@johnne, that is true. It would be a very cool idea to try out. I guess the number of samples needed is also depending on the nature of the assembly/samples involved. One could perhaps run Metaxa2 or something to try to group samples together initially. It does sound like quite some work to set it up however.

**Comment by johnne** [comment]
Yes, another option is to run sourmash to get a distance matrix of the samples, then maybe some clustering method like kmeans to cluster samples into pre-specified number of clusters.

**Comment by franciscozorrilla** [comment]
Hi @alneberg, 

As I mentioned on gitter I am now attempting the individual sample based assembly method using kallisto to generate the concoct input table. I am wondering if this is the expected output of your script (https://github.com/EnvGen/toolbox/blob/master/scripts/kallisto_concoct/input_table.py) :

[kallisto-concoct.txt](https://github.com/BinPro/CONCOCT/files/2788681/kallisto-concoct.txt)

Or should I expect to get a table with more columns such as https://github.com/BinPro/CONCOCT-test-data/blob/master/concoct-input/concoct_inputtableR.tsv ?

**Comment by alneberg** [comment]
It looks like the script has only output one coverage column. Did you give it both kallisto abundance files? Like this:

```
input_table.py sample1/abundance.txt sample2/abundance.txt --samplenames sample_names.txt
```

**Comment by franciscozorrilla** [comment]
I see, yeah I was only giving one kallisto abundance file. I modified my rule as shown below to give 2 abundance files:

```
rule kallisto2concoctTable:
    input:
        "quantification/{names}/abundance.tsv.gz"
    output:
        "concoct_input/{names}/concoct_inputtableR.tsv"
    params:
        abundance=expand("quantification/{names}/abundance.tsv.gz",names=names)
    shell:
        """
        set +u;source activate concoct_env;set -u;
        python {config[kallisto_params][script]} \
            --samplenames <(for s in $(dirname $(dirname {input}))/*; do echo $s; done) \
                {params.abundance} > {output}
        """
```

However, this results in two identical `concoct_inputtableR.tsv`.

I think my error is that I only have 2 kallisto abundance files, where I should have 4?

So I should run kallisto on sample1_R1 and sample1_R2 against kallisto_index_sample1 AS WELL as against kallisto_sample2?

**Comment by alneberg** [comment]
Since you use the variable `names` in params to denote *all* samples, and then you use the same variable in the definition for output, you will have one output for each value for `names`. I think you have to have separate variables to denote the sample that has been assembled and the sample which reads you are using to quantitate with. You would want one input table per assembly.

**Comment by franciscozorrilla** [comment]
Gotcha, ok now I see how lambda wildcards are useful. Still not exactly sure how they work but I followed what you did in `rule kallisto_concoct_inputtable` and it seems to work. Thanks again!

**Comment by franciscozorrilla** [comment]
Hi @johnne @alneberg , thanks again for all the help! 

I recently presented my thesis project but I still have some lingering doubts that you could perhaps clarify: I have read through the CONCOCT paper again, and I remain a bit uncertain about **how** the coverage across samples information is used, particularly when running CONCOCT with the per-sample-assembly-approach. I have a very vague idea of how this could work, but I am unable to explain it confidently. It seems a bit counter-intuitive that you would look at the coverage across other samples in order to bin contigs within a particular "focal sample" (as it is described in the paper). Could you please clarify this for me, or point me to the relevant section within the paper?

I am guessing that the coverage across samples information is only useful if the added samples contain some of the same bugs?

Thanks and best wishes,
Francisco

**Comment by alneberg** [comment]
Congratulations to having presenting your thesis! The original concoct paper only used co-assembly, while per-sample-assembly was used for the first time in Hugerth et al 2015. The reason to use per-sample-assembly is since the assembly itself becomes more easily handled and arguably better (for some ranges of coverage at least) as well. As I understand the main reason for you to use per-sample-assembly is since it is then more clear that the contigs within a bin is entirely originating from the focal sample.

While it might be counter-intuitive to use other than the focal sample for binning, its really the same thing as the original approach. The assumption is that very similar genomes are present in multiple samples but in varying abundance, and this information is really valuable in order to get proper binning results.

Hope this helps.

**Comment by franciscozorrilla** [comment]
Thanks again for the quick response!
Ok I think I have a better understanding now. So if we consider the following table:

![image](https://user-images.githubusercontent.com/35606471/60107153-b889ae80-9766-11e9-8c96-75242d0fb87e.png)

Then CONCOCT may bin contigs k115_5 and k115_16 together in the focal sample since they vary across samples somewhats similarly (perhaps not the best example)?

Ignoring the concrete number and thinking more visually, if I plotted the abundance each contig as a line as shown below (only two contigs shown for clarity), then CONCOCT would bin contigs/lines that have a similar profile/shape? 

![image](https://user-images.githubusercontent.com/35606471/60109092-048a2280-976a-11e9-9ea2-b47dc0833787.png)

**Comment by alneberg** [comment]
Yes that seems completely correct! I also find a similar graphical representation useful.
