### ISSUE TITLE
error running concoct test

### ISSUE THREAD

**Issue by madhubioinfo** [BinPro/CONCOCT#226]
Hi I have installed all the dependencies and trying to run concoct in centos 6 while executing test script it is showing following error
..E................
======================================================================
ERROR: test_gen_input_table.TestCMD.test_with_bamfiles
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/shared/programs/miniconda3/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/shared/programs/CONCOCT/tests/test_gen_input_table.py", line 87, in test_with_bamfiles
    sample_names = os.path.join(data_path, 'sample_names'))
  File "/shared/programs/CONCOCT/tests/test_gen_input_table.py", line 63, in run_command
    shell=True)
  File "/shared/programs/miniconda3/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'python /shared/programs/CONCOCT/tests/../scripts/gen_input_table.py --samplenames /shared/programs/CONCOCT/tests/test_data/map/sample_names /shared/programs/CONCOCT/tests/test_data/map/two_contigs.fa /shared/programs/CONCOCT/tests/test_data/map/*/*-s.bam > /shared/programs/CONCOCT/tests/nose_tmp_output/inputtable.tsv 2> /dev/null' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 19 tests in 56.022s

FAILED (errors=1)

Thanks

**Comment by alneberg** [comment]
Hello @madhubioinfo,

It seems to be some problem when running the script `scripts/gen_input_table.py`. Perhaps you could get a more informative error message if you run:

```
python /shared/programs/CONCOCT/tests/../scripts/gen_input_table.py --samplenames /shared/programs/CONCOCT/tests/test_data/map/sample_names /shared/programs/CONCOCT/tests/test_data/map/two_contigs.fa /shared/programs/CONCOCT/tests/test_data/map//*-s.bam > /shared/programs/CONCOCT/tests/nose_tmp_output/inputtable.tsv
```

**Comment by alneberg** [comment]
Glad that it worked out, even though I'm not sure I understand what caused your error in the first place?

There are I'm afraid not much documentation on the output files. The clustering file consists of two columns, one with the contig id and the other with the assigned bin id. I'd suggest using the `scripts/extract_fasta_bins.py` to get fasta bins, after using the `merge_cutup_clustering.py` script to create a new clustering file that correspond to the original contigs rather than the cutup ones.

**Comment by madhubioinfo** [comment]
there are multiple files produced here concoct_out_args.txt               concoct_out_log.txt                   concoct_out_PCA_components_data_gt1000.csv
concoct_out_clustering_gt1000.csv  concoct_out_original_data_gt1000.csv  concoct_out_PCA_transformed_data_gt1000.csv

which one I should be looking into ?

Is it especially designed for bacterial metagenomes? or even the fungal metagenomes can also be used ?

**Comment by alneberg** [comment]
Yes, `concoct_out_clustering_gt1000.csv` contains the clustering so that's the one you want to use into `merge_cutup_clustering.py`.

The other files contain information about the run, the data itself or the PCA transformation done on the data.

CONCOCT should be able to handle other than bacterial genomes. Certainly Archaeal genomes but also small Eukaryotes. Good luck!

**Comment by madhubioinfo** [comment]
thanks
