### ISSUE TITLE
CONCOCT results discussion

### ISSUE THREAD

**Issue by franciscozorrilla** [BinPro/CONCOCT#251]
Hey, I just wanted to share some of my results that I obtained from the CONCOCT portion of my pipeline and maybe get some advice. 

My dataset consisted of 137 set of paired end reads of WGS gut metagenomics information, which were quality filtered, assembled individually, and binned individually. In the figure directly below, QC refers to bin filtering using CheckM.

![image](https://user-images.githubusercontent.com/35606471/61786292-a5253e00-ae0d-11e9-8c04-6177a715fc2e.png)

While the number of pre-QC bins seems like it could corresponding to a realistic gut community, I am a bit underwhelmed by the number that makes it past the CheckM quality control, even though I used very lax filtering parameters of 40 completeness and 40 contamination. The goal of my research is to simulate metabolic interactions between the MAGs within samples, so I would like to retain as much information as possible. However, on the top right subplot you can see that there is a wide peak of pre-QC bins containing a less-than-ideal number of base pairs (i.e. due to the size I would think that they are unrealistic/incomplete bins) . 

- I am wondering if this is a commonly observed phenomenon when using CONCOCT?

- Would it be possible to implement a feature (or perhaps it already exists) where add a flag that tells CONCOCT an estimate for the smallest possible genome size in base pairs that you are expecting in your sample, so that it knows it messed up and tries to re-bin if it generates any smaller sized bins?

Through mapping the generated bins to their focal sample, I calculated how much information is lost/retained at each filtering step: 

![image](https://user-images.githubusercontent.com/35606471/61786499-1d8bff00-ae0e-11e9-95bc-36a5dd2176c1.png)

While the samples with comparatively less metagenomic information to start with are lacking in information captured after QC, overall I am pleased with the fraction of information captured by the bins in each sample (green bars). 

- However, I am wondering if you have any suggestions or recommendations that I can implement in order to push those green bars as far to the right as possible?

- Any idea why the samples with less information tend to have a lesser fraction of information captured by bins?

Thanks,
Francisco

**Comment by alneberg** [comment]
Hi @franciscozorrilla, thank you for reporting back! Your plots look really nice!

I have actually never achieved any better results than this on real samples, even though I would recommend to use a more strict checkm QC criteria.

How to improve the results better than this is an active research field I think and I can only give you my current best guess. I think you are fairly successful in retrieving high abundant prokaryotic genomes. What is harder to retrieve is mainly genomes with low abundance which could be a problem with assembly rather than binning. This would explain as well why the samples with the lowest sequencing depths are relatively less successful than the other samples.

Additionally you probably have some eukaryotic and viral sequences in your samples which will not be detected by CheckM. It is possible that some of your bins which does not make it through QC are indeed correct, but the QC methods for these genomes are more tricky to use.

Cheers,
Johannes

**Comment by franciscozorrilla** [comment]
Hey @alneberg thanks again for the feedback!

You are probably right about the filtering parameters, I will try to make them stricter if I end up publishing any of this. I was not initially very concerned with the filtering parameters, as I have been using the binned MAGs to generate species specific GEMs with this [top-down-reconstruction-approach tool](https://academic.oup.com/nar/article/46/15/7542/5042022), so the bins dont need to be perfect but yes it would be better if they are as accurate/complete as possible.

Somewhat unrelated, have you tried using any of these new(ish) machine/deep learning methods for [assembly](https://academic.oup.com/bib/advance-article/doi/10.1093/bib/bby072/5074612#120142870), [ binning](https://www.biorxiv.org/content/10.1101/490078v2), [taxonomic classification](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2182-6), etc? 

I am not very familiar with these methods but perhaps I will give them a shot to see if they improve my results.

Best wishes,
Francisco

**Comment by alneberg** [comment]
I don't think it's unimportant to do strict filtering for GEMs, since you can end up with pathways that doesn't actually exist if you have high contamination and you can end up with two bins for the same genome if you have low completeness (<50%).

Sorry, I haven't tried any of the modern tools, but happy to hear back from you about your results. I'll close this issue now but you're welcome to answer back as you wish. Cheers!
